name: imeet
excludes:
    - var
    - node_modules
    - vendor
recipe: symfony
config:
    php: 8.1
    via: nginx
    webroot: public
    mysql: 5.7

proxy:
    mailpit:
        - mailpit.imeet.lndo.site:8025
services:
    appserver:
        xdebug: true
        overrides:
            environment:
                PHP_IDE_CONFIG: "serverName=appserver"
    
    database:
        portforward: 3306
        creds:
            user: amad
            password: amad
            database: imeet
    node:
        type: node
        build:
            - npm install
    mailpit:
      type: compose
      ssl: true
      app_mount: false
      # uniquement ssl par le proxy
      sslExpose: false
      # pour exposer en localhost sans proxy (mapping auto)
      moreHttpPorts:
        - 8025
      services:
        image: axllent/mailpit
        command: /mailpit
        environment:
          MP_MAX_MESSAGES: 5000
        # pour exposer en localhost
        ports:
          - 8025
    phpmyadmin:
        type: phpmyadmin:5.0
        hosts:
            - database
tooling:
    sf:
        service: appserver
        description: Run Symfony commands
        cmd:
            - bin/console
    cc:
        service: appserver
        description: Run Symfony commands
        cmd:
            - "XDEBUG_MODE=off bin/console cache:clear && XDEBUG_MODE=on"
    npm:
        service: node
